name: Pipeline de Teste

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17 with Maven
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: adopt

    - name: Build and Test
      run: mvn clean test

    - name: Jacoco Report
      run: mvn jacoco:report

    - name: Verify Code Coverage
      run: |
        COVERAGE=$(awk '/Total/{print $NF}' target/site/jacoco/jacoco.xml | cut -d "." -f 1)
        COVERAGE2=$(grep -A 1 '(?<=<td>Total<\/td>\n<td class="bar">[0-9]+ of [0-9]+<\/td>\n<td class="ctr2">)[0-9]+(?=%<\/td>)' target/site/jacoco/index.html | tail -n 1 | cut -d '>' -f 2 | cut -d '<' -f 1)
        COVERAGE3=$(awk -F'[<>]' '/report type="INSTRUCTION"/{print $3}' target/site/jacoco/index.html)
        echo COVERAGE
        echo COVERAGE2
        echo COVERAGE3
        if [ "$COVERAGE" -ge "70" ]; then
          echo "Code coverage is $COVERAGE%. Test passed!"
        else
          echo "Code coverage is $COVERAGE%. Test failed!"
        exit 1
        fi
        
